#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Api\UpdateApiCommand());
$application->add(new \Api\ApiStatusCommand());
$application->add(new \Api\ApiUninstallCommand());
$application->add(new \Api\RestartContainersCommand());
$application->add(new \Api\StartContainersCommand());
$application->add(new \Api\KillContainersCommand());
$application->add(new \Api\StopContainersCommand());
$application->add(new \Api\InstallApiCommand());

$application->run();
